In [ ]:
import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta
from tqdm import tqdm
import os
import pyodbc
from dotenv import load_dotenv

load_dotenv()

In [2]:
fake = Faker('en_US')

In [3]:
NUM_CUSTOMERS = 10000

In [4]:
countries = [
    "Germany",
    "Netherlands",
    "France",
    "United Kingdom",
    "Sweden",
    "Austria",
    "Belgium"
]

country_weights = [
    40,
    15,
    15,
    10,
    8,
    7,
    5
]

In [5]:
country_cities = {
    "Germany": [
        "Berlin",
        "Munich",
        "Hamburg",
        "Frankfurt"
    ],
    
    "Netherlands": [
        "Amsterdam",
        "Rotterdam",
        "Utrecht"
    ],
    
    "France": [
        "Paris",
        "Lyon",
        "Marseille"
    ],
    
    "United Kingdom": [
        "London",
        "Manchester",
        "Birmingham"
    ],
    
    "Sweden": [
        "Stockholm",
        "Gothenburg"
    ],
    
    "Austria": [
        "Vienna",
        "Salzburg"
    ],
    
    "Belgium": [
        "Brussels",
        "Antwerp"
    ]
}

In [6]:
acquisition_channels = {
    1: "Organic Search",
    2: "Google Ads",
    3: "Facebook Ads",
    4: "Referral",
    5: "Email Marketing"
}

In [7]:
channel_ids = [
    1,
    2,
    3,
    4,
    5
]

channel_weights = [
    40,
    25,
    15,
    10,
    10
]

In [8]:
customer_statuses = {
    1: "Active",
    2: "Inactive",
    3: "Churned"
}

In [9]:
status_ids = [
    1,
    2,
    3
]

status_weights = [
    80,
    15,
    5
]

In [ ]:
customers = []

for i in range(NUM_CUSTOMERS):

    first_name = fake.first_name()
    last_name = fake.last_name()

    country = random.choices(
        countries,
        weights=country_weights
    )[0]

    city = random.choices(
        country_cities[country]
    )[0]

    start_date = datetime(2023, 1, 1)
    end_date = datetime(2026, 8, 1)

    customer = {
        "FirstName": first_name,
        "LastName": last_name,
        "Email": f"{first_name.lower()}.{last_name.lower()}{i}@gmail.com",
        "PhoneNumber": fake.phone_number(),
        "Gender": random.choices(
            ["Male", "Female"],
            weights=[45, 55]
        )[0],
        "DateOfBirth": fake.date_of_birth(
            minimum_age=18,
            maximum_age=70
        ),
        "Country": country,
        "City": city,
        "SignupDate": fake.date_between(
            start_date=start_date,
            end_date=end_date
        ),
        "acquisition_channel_id": random.choices(
            channel_ids,
            weights=channel_weights
        )[0],
        "CustomerStatusID": random.choices(
            status_ids,
            weights=status_weights
        )[0]
    }

    customers.append(customer)

In [11]:
customer_df = pd.DataFrame(customers)
customer_df.head(10)

,FirstName,LastName,Email,PhoneNumber,Gender,DateOfBirth,Country,City,SignupDate,acquisition_channel_id,CustomerStatusID
0,Edward,Rogers,edward.rogers0@gmail.com,438.661.0995x2747,Male,1969-04-12,Sweden,Stockholm,2023-05-19,5,1
1,Jennifer,Warren,jennifer.warren1@gmail.com,960-674-8149x1339,Female,1968-05-19,Belgium,Brussels,2024-12-20,2,1
2,Joseph,Austin,joseph.austin2@gmail.com,358.426.1986x3157,Male,1968-10-14,Netherlands,Rotterdam,2023-11-23,3,2
3,Brenda,White,brenda.white3@gmail.com,001-833-386-7162x464,Male,2007-01-15,United Kingdom,Birmingham,2026-03-04,3,1
4,Emily,Hernandez,emily.hernandez4@gmail.com,368-874-5505x220,Female,1982-06-04,Netherlands,Rotterdam,2025-10-11,1,1
5,Natalie,Matthews,natalie.matthews5@gmail.com,895-256-2152,Male,2005-09-10,Germany,Munich,2026-06-22,2,1
6,Cindy,Goodman,cindy.goodman6@gmail.com,+1-482-627-0329,Male,2005-08-03,France,Paris,2025-08-28,3,1
7,Diana,Robinson,diana.robinson7@gmail.com,254.761.3548,Male,2006-02-09,Sweden,Stockholm,2024-10-17,1,1
8,Laura,Wagner,laura.wagner8@gmail.com,6236671382,Female,1999-10-06,Sweden,Stockholm,2024-04-15,3,2
9,Elizabeth,Perry,elizabeth.perry9@gmail.com,298.911.4358x2242,Female,1996-06-07,Germany,Berlin,2023-06-23,3,1

In [12]:
customer_df.insert(
    0,
    "CustomerID",
    range(1, len(customer_df) + 1)
)

In [15]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              10000 non-null  int64
 1   FirstName               10000 non-null  object
 2   LastName                10000 non-null  object
 3   Email                   10000 non-null  object
 4   PhoneNumber             10000 non-null  object
 5   Gender                  10000 non-null  object
 6   DateOfBirth             10000 non-null  object
 7   Country                 10000 non-null  object
 8   City                    10000 non-null  object
 9   SignupDate              10000 non-null  object
 10  acquisition_channel_id  10000 non-null  int64
 11  CustomerStatusID        10000 non-null  int64
dtypes: int64(3), object(9)
memory usage: 937.6+ KB

In [16]:
product_categories = {
    1: "Electronics",
    2: "Beauty",
    3: "Clothing",
    4: "Home",
    5: "Sports"
}

In [17]:
product_names = {
    "Electronics": [
        "Laptop",
        "Wireless Mouse",
        "Mechanical Keyboard",
        "Monitor",
        "Headphones"
    ],

    "Beauty": [
        "Face Cream",
        "Perfume",
        "Shampoo",
        "Body Lotion"
    ],

    "Clothing": [
        "T-Shirt",
        "Jeans",
        "Jacket",
        "Sneakers"
    ],

    "Home": [
        "Coffee Maker",
        "Vacuum Cleaner",
        "Desk Lamp"
    ],

    "Sports": [
        "Football",
        "Yoga Mat",
        "Tennis Racket",
        "Dumbbells"
    ]
}

In [18]:
category_rules = {
    "Electronics": {
        "price_range": (300, 2000),
        "brands": ["Apple", "Samsung", "Dell", "HP", "Sony"]
    },

    "Beauty": {
        "price_range": (10, 150),
        "brands": ["Loreal", "Nivea", "Maybelline", "Dove"]
    },

    "Clothing": {
        "price_range": (20, 250),
        "brands": ["Nike", "Adidas", "Puma", "Zara"]
    },

    "Home": {
        "price_range": (40, 800),
        "brands": ["IKEA", "Philips", "Bosch"]
    },

    "Sports": {
        "price_range": (30, 500),
        "brands": ["Nike", "Adidas", "Wilson", "Puma"]
    }
}

In [ ]:
category = random.choices(list(category_rules.keys()))[0]

brand = random.choices(
    category_rules[category]["brands"]
)[0]

price = round(
    random.uniform(
        category_rules[category]["price_range"][0],
        category_rules[category]["price_range"][1]
    ),
    2
)

x = f"{category}-{brand}-{price}"

print(x)

In [20]:
NUM_PRODUCTS = 500

In [ ]:
products = []

for i in range(NUM_PRODUCTS):

    category_id = random.choice(list(product_categories.keys()))
    category = product_categories[category_id]

    product_name = random.choice(product_names[category])
    brand = random.choice(category_rules[category]["brands"])

    min_price, max_price = category_rules[category]["price_range"]

    price = round(
        random.uniform(min_price, max_price),
        2
    )

    cost = round(
        price * random.uniform(0.5, 0.8),
        2
    )

    product = {
        "CategoryID": category_id,
        # "CategoryName": category,
        "ProductName": product_name,
        "Brand": brand,
        "Price": price,
        "Cost": cost
    }

    products.append(product)

In [22]:
Product_df = pd.DataFrame(products)
Product_df.head(5)

   CategoryID          ProductName       Brand    Price     Cost
0           1  Mechanical Keyboard       Apple  1560.96  1202.83
1           2           Face Cream  Maybelline    70.38    40.48
2           3             Sneakers        Puma   174.83   121.98
3           1              Monitor       Apple   344.57   188.54
4           4         Coffee Maker       Bosch   123.80    79.34

In [23]:
Product_df.shape

(500, 5)

In [24]:
(Product_df["Cost"] > Product_df["Price"]).sum()

np.int64(0)

In [25]:
NUM_ORDERS = 20000

In [26]:
customer_df.sample(1).iloc[0]

CustomerID                                          7483
FirstName                                       Michelle
LastName                                         Freeman
Email                     michelle.freeman7482@gmail.com
PhoneNumber                                   4975922026
Gender                                            Female
DateOfBirth                                   1956-03-12
Country                                          Austria
City                                              Vienna
SignupDate                                    2023-01-18
acquisition_channel_id                                 1
CustomerStatusID                                       1
Name: 7482, dtype: object

In [27]:
payment_methods = {
    "Credit Card": 1,
    "PayPal": 2,
    "Bank Transfer": 3,
    "Cash on Delivery": 4
}

In [28]:
order_statuses = {
    "Pending": 1,
    "Processing": 2,
    "Delivered": 3,
    "Cancelled": 4
}

In [29]:
orders = []

for i in range(NUM_ORDERS):

    customer = customer_df.sample().iloc[0]

    customer_id = customer["CustomerID"]
    signup_date = customer["SignupDate"]

    order_date = fake.date_between(
        start_date=signup_date,
        end_date="today"
    )

    payment_method_id = random.choice(
        list(payment_methods.values())
    )

    order_status_id = random.choice(
        list(order_statuses.values())
    )

    order = {
        "CustomerID": customer_id,
        "OrderDate": order_date,
        "PaymentMethodID": payment_method_id,
        "OrderStatusID": order_status_id
    }

    orders.append(order)

In [30]:
orders_df = pd.DataFrame(orders)
orders_df.head(5)

   CustomerID   OrderDate  PaymentMethodID  OrderStatusID
0        1028  2026-05-28                2              2
1        7682  2026-02-05                2              1
2        5520  2025-04-07                2              1
3        6242  2024-05-27                1              1
4        4545  2026-01-21                3              1

In [31]:
orders_df["CustomerID"].isin(
    customer_df["CustomerID"]
).all()

np.True_

In [32]:
check_df = orders_df.merge(
    customer_df[["CustomerID", "SignupDate"]],
    on="CustomerID"
)

In [33]:
check_df

       CustomerID   OrderDate  PaymentMethodID  OrderStatusID  SignupDate
0            1028  2026-05-28                2              2  2025-01-06
1            7682  2026-02-05                2              1  2023-09-24
2            5520  2025-04-07                2              1  2024-04-18
3            6242  2024-05-27                1              1  2024-05-09
4            4545  2026-01-21                3              1  2024-07-09
...           ...         ...              ...            ...         ...
19995        9279  2025-10-01                2              2  2024-04-11
19996        5601  2025-09-12                1              3  2023-02-23
19997         286  2023-10-18                3              4  2023-10-06
19998        5081  2025-12-28                3              1  2023-10-03
19999        5712  2024-09-24                4              1  2023-11-25

[20000 rows x 5 columns]

In [34]:
check_df["OrderDate"] < check_df["SignupDate"]

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Length: 20000, dtype: bool

In [ ]:
orders_df.insert(
    0,
    "OrderID",
    range(1, len(orders_df) + 1)
)

In [36]:
orders_df

       OrderID  CustomerID   OrderDate  PaymentMethodID  OrderStatusID
0            1        1028  2026-05-28                2              2
1            2        7682  2026-02-05                2              1
2            3        5520  2025-04-07                2              1
3            4        6242  2024-05-27                1              1
4            5        4545  2026-01-21                3              1
...        ...         ...         ...              ...            ...
19995    19996        9279  2025-10-01                2              2
19996    19997        5601  2025-09-12                1              3
19997    19998         286  2023-10-18                3              4
19998    19999        5081  2025-12-28                3              1
19999    20000        5712  2024-09-24                4              1

[20000 rows x 5 columns]

In [37]:
Product_df

     CategoryID          ProductName       Brand    Price     Cost
0             1  Mechanical Keyboard       Apple  1560.96  1202.83
1             2           Face Cream  Maybelline    70.38    40.48
2             3             Sneakers        Puma   174.83   121.98
3             1              Monitor       Apple   344.57   188.54
4             4         Coffee Maker       Bosch   123.80    79.34
..          ...                  ...         ...      ...      ...
495           2              Shampoo      Loreal   142.00   110.33
496           1           Headphones        Dell  1270.09   930.85
497           1              Monitor       Apple   657.00   379.85
498           5             Football        Nike   468.73   312.05
499           2              Perfume  Maybelline    27.92    19.59

[500 rows x 5 columns]

In [ ]:
Product_df.insert(
    0,
    "ProductID",
    range(1, len(Product_df) + 1)
)

In [ ]:
order_items = []

for _, order in orders_df.iterrows():

    order_id = order["OrderID"]
    num_items = random.randint(1, 5)

    selected_products = Product_df.sample(num_items)

    for _, product in selected_products.iterrows():

        quantity = random.randint(1, 4)

        order_item = {
            "OrderID": order_id,
            "ProductID": product["ProductID"],
            "Quantity": quantity,
            "UnitPrice": product["Price"]
        }

        order_items.append(order_item)

In [ ]:
order_items_df = pd.DataFrame(order_items)

order_items_df["LineTotal"] = (
    order_items_df["UnitPrice"]
    * order_items_df["Quantity"]
)

order_items_df.head()

   OrderID  ProductID  Quantity  UnitPrice  LineTotal
0        1         45         3     361.67    1085.01
1        1         92         3     148.81     446.43
2        1        302         4     790.78    3163.12
3        2        357         2     671.92    1343.84
4        2        376         2     174.62     349.24

In [41]:
order_items_df.shape

(60075, 5)

In [42]:
order_items_df["OrderID"].nunique()

20000

In [43]:
order_items_df["ProductID"].nunique()

500

In [ ]:
order_totals = (order_items_df.groupby("OrderID")["LineTotal"].sum().reset_index())
order_totals

       OrderID  LineTotal
0            1    4694.56
1            2    1693.08
2            3      58.48
3            4    1881.13
4            5    2801.19
...        ...        ...
19995    19996    7190.21
19996    19997    4285.66
19997    19998     381.77
19998    19999    4326.10
19999    20000    1602.09

[20000 rows x 2 columns]

In [45]:
orders_df

       OrderID  CustomerID   OrderDate  PaymentMethodID  OrderStatusID
0            1        1028  2026-05-28                2              2
1            2        7682  2026-02-05                2              1
2            3        5520  2025-04-07                2              1
3            4        6242  2024-05-27                1              1
4            5        4545  2026-01-21                3              1
...        ...         ...         ...              ...            ...
19995    19996        9279  2025-10-01                2              2
19996    19997        5601  2025-09-12                1              3
19997    19998         286  2023-10-18                3              4
19998    19999        5081  2025-12-28                3              1
19999    20000        5712  2024-09-24                4              1

[20000 rows x 5 columns]

In [46]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          20000 non-null  int64
 1   CustomerID       20000 non-null  int64
 2   OrderDate        20000 non-null  object
 3   PaymentMethodID  20000 non-null  int64
 4   OrderStatusID    20000 non-null  int64
dtypes: int64(4), object(1)
memory usage: 781.4+ KB

In [47]:
order_totals.head()

   OrderID  LineTotal
0        1    4694.56
1        2    1693.08
2        3      58.48
3        4    1881.13
4        5    2801.19

In [48]:
order_totals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    20000 non-null  int64
 1   LineTotal  20000 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 312.6 KB

In [49]:
orders_df = orders_df.merge(
    order_totals,
    on="OrderID",
    how = "left"
)

In [50]:
orders_df.rename(
    columns={"LineTotal": "TotalAmount"},
    inplace=True
)

In [51]:
orders_df

,OrderID,CustomerID,OrderDate,PaymentMethodID,OrderStatusID,TotalAmount
0,1,1028,2026-05-28,2,2,4694.56
1,2,7682,2026-02-05,2,1,1693.08
2,3,5520,2025-04-07,2,1,58.48
3,4,6242,2024-05-27,1,1,1881.13
4,5,4545,2026-01-21,3,1,2801.19
...,...,...,...,...,...,...
19995,19996,9279,2025-10-01,2,2,7190.21
19996,19997,5601,2025-09-12,1,3,4285.66
19997,19998,286,2023-10-18,3,4,381.77
19998,19999,5081,2025-12-28,3,1,4326.10
19999,20000,5712,2024-09-24,4,1,1602.09

In [ ]:
conn = pyodbc.connect(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={os.getenv('DB_SERVER')};"
    f"DATABASE={os.getenv('DB_DATABASE')};"
    f"UID={os.getenv('DB_USERNAME')};"
    f"PWD={os.getenv('DB_PASSWORD')};"
	"Trusted_Connection=yes;"
)

cursor = conn.cursor()

In [ ]:
cursor.execute("SELECT @@VERSION")

print(cursor.fetchone())

('Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64) \n\tOct  8 2022 05:58:25 \n\tCopyright (C) 2022 Microsoft Corporation\n\tEnterprise Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 26100: )\n',)

In [55]:
cursor.execute("SELECT *FROM DeviceTypes")
rows = cursor.fetchall()

cursor.description

(('DeviceTypeID', int, None, 10, 10, 0, False),
 ('DeviceTypeName', str, None, 30, 30, 0, False),
 ('Description', str, None, 255, 255, 0, True),
 ('CreatedAt', datetime.datetime, None, 27, 27, 7, False))

In [56]:
def run_query(query):

    cursor.execute(query)

    rows = cursor.fetchall()

    columns = [column[0] for column in cursor.description]

    df = pd.DataFrame.from_records(rows, columns=columns)

    return df

In [57]:
device_types_df = run_query("SELECT * FROM DeviceTypes")
device_types_df

   DeviceTypeID DeviceTypeName        Description                  CreatedAt
0             1        Desktop  Desktop or Laptop 2026-07-25 18:09:44.826828
1             2         Mobile         Smartphone 2026-07-25 18:09:44.826828
2             3         Tablet      Tablet device 2026-07-25 18:09:44.826828
3             4       Smart TV   Smart television 2026-07-25 18:09:44.826828
4             5          Other      Other devices 2026-07-25 18:09:44.826828

In [58]:
cursor.execute("SELECT * FROM DeviceTypes")

rows = cursor.fetchall()

print(rows)
print(type(rows))
print(type(rows[0]))

[(1, 'Desktop', 'Desktop or Laptop', datetime.datetime(2026, 7, 25, 18, 9, 44, 826828)), (2, 'Mobile', 'Smartphone', datetime.datetime(2026, 7, 25, 18, 9, 44, 826828)), (3, 'Tablet', 'Tablet device', datetime.datetime(2026, 7, 25, 18, 9, 44, 826828)), (4, 'Smart TV', 'Smart television', datetime.datetime(2026, 7, 25, 18, 9, 44, 826828)), (5, 'Other', 'Other devices', datetime.datetime(2026, 7, 25, 18, 9, 44, 826828))]
<class 'list'>
<class 'pyodbc.Row'>

In [59]:
print([col[0] for col in cursor.description])

['DeviceTypeID', 'DeviceTypeName', 'Description', 'CreatedAt']

In [60]:
cursor.execute("SELECT DB_NAME()")

print(cursor.fetchone())

('BloomCart',)

In [61]:
cursor.execute("""
SELECT COUNT(*) FROM Customers;
""")

print(cursor.fetchone())

(40001,)

In [62]:
conn.commit()
conn.close()

In [63]:
# customer_df = customer_df.drop(columns=["CustomerID"])
customer_df.rename(
    columns={
        "acquisition_channel_id": "AcquisitionChannelID"
    },
    inplace=True
)
# columns = customer_df.columns.tolist()
# column_names = ", ".join(columns)
# column_names

In [64]:
# placeholders = ", ".join(["?"] * len(columns))

# placeholders

In [65]:
# query = f"""
# INSERT INTO Customers
# ({", ".join(columns)})
# VALUES
# ({placeholders})
# """

In [66]:
# print(query)

In [67]:
# customer_df.head()

In [68]:
# row = tuple(customer_df.iloc[0])

# row

In [69]:
# row = tuple(
#     int(x) if isinstance(x, np.integer) else x
#     for x in customer_df.iloc[0]
# )

In [70]:
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=DESKTOP-50K2UR1;"
    "DATABASE=BloomCart;"
    "Trusted_Connection=yes;"
    "UID=sa;"
    "PWD=12345678;"
)

cursor = conn.cursor()

In [71]:
customers_check = run_query("""
SELECT TOP 5 *
FROM Customers
""")

customers_check

,CustomerID,FirstName,LastName,Email,PhoneNumber,Gender,DateOfBirth,Country,City,SignupDate,AcquisitionChannelID,CustomerStatusID,CreatedAt
0,4,Sean,Rose,sean.rose@gmail.com,+1-764-253-2460x012,Male,1996-12-16,Germany,Munich,2023-08-07,1,1,2026-08-06 14:15:52.931257
1,10005,Thomas,Willis,thomas.willis0@gmail.com,001-514-430-3105,Male,1972-03-01,Netherlands,Rotterdam,2024-01-16,2,2,2026-08-06 15:30:30.865823
2,10006,Jamie,Morris,jamie.morris1@gmail.com,001-262-885-2870x9686,Female,1964-05-01,Germany,Munich,2024-06-07,2,1,2026-08-06 15:30:30.867845
3,10007,Carla,Jones,carla.jones2@gmail.com,001-843-559-0592x6459,Female,1997-12-15,Austria,Vienna,2026-05-21,1,2,2026-08-06 15:30:30.867845
4,10008,Sherry,Garcia,sherry.garcia3@gmail.com,5649346329,Male,1965-03-18,Germany,Frankfurt,2023-06-12,5,1,2026-08-06 15:30:30.867845

In [72]:
def insert_dataframe(df, table_name,exclude_columns=[]):
    
    df = df.drop(columns=exclude_columns,errors="ignore")
    
    columns = df.columns.tolist()
    
    column_names = ", ".join(columns)
    
    placeholders = ", ".join(["?"] * len(columns))

    query = f"""
    INSERT INTO {table_name}
    ({column_names})
    VALUES
    ({placeholders})
    """

    data = [
        tuple(row)
        for row in df.itertuples(index=False, name=None)
    ]

    cursor.fast_executemany = True
    cursor.executemany(query, data)

    conn.commit()

In [73]:
duplicates = (
    customer_df[customer_df["Email"].duplicated(keep=False)]
    .sort_values("Email")
)

duplicates

Empty DataFrame
Columns: [CustomerID, FirstName, LastName, Email, PhoneNumber, Gender, DateOfBirth, Country, City, SignupDate, AcquisitionChannelID, CustomerStatusID]
Index: []

In [74]:
customer_df.shape

(10000, 12)

In [75]:
customers_check = run_query("""
SELECT COUNT(*) AS TotalCustomers
FROM Customers
""")

customers_check

   TotalCustomers
0           40001

In [76]:
run_query("""
SELECT TOP 5 *
FROM Customers
""")

,CustomerID,FirstName,LastName,Email,PhoneNumber,Gender,DateOfBirth,Country,City,SignupDate,AcquisitionChannelID,CustomerStatusID,CreatedAt
0,4,Sean,Rose,sean.rose@gmail.com,+1-764-253-2460x012,Male,1996-12-16,Germany,Munich,2023-08-07,1,1,2026-08-06 14:15:52.931257
1,10005,Thomas,Willis,thomas.willis0@gmail.com,001-514-430-3105,Male,1972-03-01,Netherlands,Rotterdam,2024-01-16,2,2,2026-08-06 15:30:30.865823
2,10006,Jamie,Morris,jamie.morris1@gmail.com,001-262-885-2870x9686,Female,1964-05-01,Germany,Munich,2024-06-07,2,1,2026-08-06 15:30:30.867845
3,10007,Carla,Jones,carla.jones2@gmail.com,001-843-559-0592x6459,Female,1997-12-15,Austria,Vienna,2026-05-21,1,2,2026-08-06 15:30:30.867845
4,10008,Sherry,Garcia,sherry.garcia3@gmail.com,5649346329,Male,1965-03-18,Germany,Frankfurt,2023-06-12,5,1,2026-08-06 15:30:30.867845

In [77]:
Product_df.head()

   ProductID  CategoryID          ProductName       Brand    Price     Cost
0          1           1  Mechanical Keyboard       Apple  1560.96  1202.83
1          2           2           Face Cream  Maybelline    70.38    40.48
2          3           3             Sneakers        Puma   174.83   121.98
3          4           1              Monitor       Apple   344.57   188.54
4          5           4         Coffee Maker       Bosch   123.80    79.34

In [78]:
Product_df.columns

Index(['ProductID', 'CategoryID', 'ProductName', 'Brand', 'Price', 'Cost'], dtype='object')

In [ ]:
Product_df["StockQuantity"] = [
    random.randint(0, 500)
    for _ in range(len(Product_df))
]

In [80]:
Product_df.head()

,ProductID,CategoryID,ProductName,Brand,Price,Cost,StockQuantity
0,1,1,Mechanical Keyboard,Apple,1560.96,1202.83,422
1,2,2,Face Cream,Maybelline,70.38,40.48,322
2,3,3,Sneakers,Puma,174.83,121.98,493
3,4,1,Monitor,Apple,344.57,188.54,75
4,5,4,Coffee Maker,Bosch,123.80,79.34,366

In [81]:
sorted(Product_df["CategoryID"].unique())

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [82]:
run_query("""
SELECT CategoryID
FROM ProductCategories
ORDER BY CategoryID
""")

   CategoryID
0           1
1           2
2           3
3           4

In [83]:
product_categories = run_query("""
SELECT CategoryID
FROM ProductCategories
""")

valid_categories = set(product_categories["CategoryID"])

invalid_categories = set(Product_df["CategoryID"]) - valid_categories

invalid_categories

{5}

In [84]:
valid_category_ids = product_categories["CategoryID"].tolist()

Product_df["CategoryID"] = [
    random.choice(valid_category_ids)
    for _ in range(len(Product_df))
]

In [85]:
sorted(Product_df["CategoryID"].unique())

[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [86]:
insert_dataframe(
    Product_df,
    "Products",
    exclude_columns=["ProductID", "CreatedAt"]
)

In [ ]:
x= run_query("""
SELECT * FROM Products
""")
x

,ProductID,ProductName,CategoryID,Brand,Price,Cost,StockQuantity,CreatedAt
0,2,Dior Sauvage,1,Dior,120.00,70.00,50,2026-07-25 18:26:20.116693
1,3,CeraVe Cleanser,2,CeraVe,25.00,12.00,100,2026-07-25 18:26:20.116693
2,504,Coffee Maker,4,Bosch,596.32,311.51,214,2026-08-11 10:34:58.200848
3,505,Mechanical Keyboard,1,Sony,595.31,377.94,405,2026-08-11 10:34:58.206441
4,506,Vacuum Cleaner,4,IKEA,398.31,238.14,115,2026-08-11 10:34:58.206441
...,...,...,...,...,...,...,...,...
3329,3999,Shampoo,1,Loreal,142.00,110.33,236,2026-08-16 17:08:37.655995
3330,4000,Headphones,1,Dell,1270.09,930.85,126,2026-08-16 17:08:37.655995
3331,4001,Monitor,1,Apple,657.00,379.85,34,2026-08-16 17:08:37.655995
3332,4002,Football,1,Nike,468.73,312.05,130,2026-08-16 17:08:37.655995
3333,4003,Perfume,1,Maybelline,27.92,19.59,419,2026-08-16 17:08:37.655995

In [88]:
orders_df.shape

(20000, 6)

In [89]:
orders_df.columns

Index(['OrderID', 'CustomerID', 'OrderDate', 'PaymentMethodID',
       'OrderStatusID', 'TotalAmount'],
      dtype='object')

In [ ]:
y = run_query("""
SELECT *
FROM Orders
ORDER BY OrderID
""")

y

,OrderID,CustomerID,OrderDate,OrderStatusID,PaymentMethodID,TotalAmount,CreatedAt
0,101001,39231,2024-08-10,3,3,11551.79,2026-08-11 11:32:21.176768
1,101002,10048,2025-10-04,4,4,10716.44,2026-08-11 11:32:21.181030
2,101003,14704,2026-06-11,4,2,2273.82,2026-08-11 11:32:21.183567
3,101004,44229,2026-04-20,4,1,6209.88,2026-08-11 11:32:21.184566
4,101005,13591,2026-03-10,3,3,5420.16,2026-08-11 11:32:21.184566
...,...,...,...,...,...,...,...
39995,141996,30697,2026-02-25,1,3,7978.86,2026-08-11 12:42:42.096966
39996,141997,37656,2025-11-22,1,1,1099.28,2026-08-11 12:42:42.096966
39997,141998,35600,2025-05-17,2,4,502.64,2026-08-11 12:42:42.096966
39998,141999,10989,2026-08-08,1,3,2149.73,2026-08-11 12:42:42.096966
39999,142000,29256,2024-09-19,1,4,3914.52,2026-08-11 12:42:42.096966

In [ ]:

conn.commit()

In [92]:
orders_df.shape

(20000, 6)

In [ ]:
def insert_dataframe2(
    df,
    table_name,
    exclude_columns=[],
    batch_size=1000
):
    df = df.drop(
        columns=exclude_columns,
        errors="ignore"
    )

    columns = df.columns.tolist()
    column_names = ", ".join(columns)
    placeholders = ", ".join(["?"] * len(columns))

    query = f"""
    INSERT INTO {table_name} ({column_names})
    VALUES ({placeholders})
    """

    data = [
        tuple(row)
        for row in df.itertuples(
            index=False,
            name=None
        )
    ]

    try:
        cursor.fast_executemany = True

        for start in tqdm(
            range(0, len(data), batch_size),
            desc=f"Inserting into {table_name}"
        ):
            batch = data[start:start + batch_size]

            cursor.executemany(
                query,
                batch
            )

            conn.commit()

    except Exception as e:
        conn.rollback()

        print("Insert failed. Transaction rolled back.")
        print(e)

In [94]:
insert_dataframe2(
    orders_df,
    "Orders",
    exclude_columns=["OrderID", "CreatedAt"],
    batch_size=1000
)

Inserting into Orders:   0%|          | 0/20 [00:01<?, ?it/s]

Insert failed. Transaction rolled back.

In [95]:
customers_sql = run_query("""
SELECT CustomerID
FROM Customers
""")

valid_customer_ids = set(customers_sql["CustomerID"])

invalid_customer_ids = (
    set(orders_df["CustomerID"]) - valid_customer_ids
)

invalid_customer_ids

{2,
 3,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 53,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 68,
 69,
 70,
 73,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 139,
 140,
 141,
 142,
 144,
 145,
 147,
 149,
 150,
 151,
 152,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 170,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 184,
 185,
 186,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 230,
 231,
 232,
 233,
 235,
 236,
 237,
 238,
 239,
 241,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 270,
 271,
 272,
 273,
 274,
 276,
 277,
 278,
 279,
 280,
 282,
 283,
 284,
 286,
 287,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 331,
 332,
 333,
 334,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 349,
 350,
 351,
 352,
 353,
 354,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 392,
 393,
 394,
 395,
 397,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 464,
 466,
 467,
 469,
 470,
 471,
 473,
 474,
 475,
 476,
 477,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 500,
 501,
 502,
 503,
 505,
 506,
 507,
 508,
 510,
 511,
 512,
 513,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 532,
 533,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 549,
 551,
 552,
 554,
 555,
 556,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 577,
 578,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 588,
 589,
 590,
 592,
 593,
 594,
 595,
 596,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 609,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 629,
 630,
 631,
 632,
 633,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 662,
 663,
 664,
 665,
 666,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 701,
 703,
 704,
 705,
 707,
 708,
 709,
 710,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 740,
 741,
 742,
 743,
 744,
 746,
 747,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 761,
 762,
 763,
 764,
 766,
 767,
 768,
 769,
 771,
 772,
 773,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 792,
 793,
 794,
 795,
 796,
 798,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 813,
 814,
 815,
 816,
 817,
 818,
 820,
 821,
 822,
 825,
 826,
 827,
 828,
 829,
 831,
 832,
 833,
 836,
 837,
 838,
 839,
 840,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 854,
 856,
 857,
 858,
 860,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 878,
 879,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 891,
 892,
 893,
 895,
 896,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 912,
 913,
 914,
 916,
 917,
 918,
 919,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 931,
 932,
 933,
 934,
 936,
 939,
 940,
 941,
 943,
 944,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 976,
 977,
 978,
 979,
 980,
 981,
 983,
 984,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 996,
 997,
 998,
 999,
 1000,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1011,
 1012,
 1013,
 1014,
 1016,
 1017,
 1018,
 1020,
 1021,
 1022,
 1024,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1058,
 1059,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1093,
 1094,
 1096,
 1097,
 1098,
 1099,
 1100,
 1101,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1114,
 1115,
 1118,
 1119,
 1120,
 1121,
 1123,
 1124,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1133,
 1135,
 1136,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 ...}

In [96]:
customers_sql = run_query("""
SELECT CustomerID
FROM Customers
""")

valid_customer_ids = customers_sql["CustomerID"].tolist()

In [97]:
valid_customer_ids

[25401,
 19155,
 10449,
 30517,
 16313,
 21469,
 37462,
 18765,
 26437,
 38063,
 40558,
 25292,
 32264,
 49985,
 32275,
 39397,
 46114,
 33504,
 25268,
 47977,
 40508,
 37278,
 40888,
 48930,
 11021,
 25261,
 24348,
 19626,
 45653,
 12712,
 28338,
 42265,
 14076,
 47714,
 10408,
 26469,
 12907,
 48870,
 20927,
 22690,
 47256,
 34121,
 19075,
 40225,
 34887,
 12208,
 11444,
 37736,
 46662,
 11795,
 39316,
 45912,
 38982,
 38367,
 17199,
 25359,
 10269,
 19795,
 32217,
 41275,
 38519,
 37318,
 43787,
 47321,
 24156,
 24567,
 25779,
 20688,
 10976,
 15079,
 34242,
 13781,
 46419,
 12100,
 31585,
 43965,
 17886,
 13151,
 14723,
 24181,
 37309,
 25925,
 16801,
 39321,
 14210,
 31676,
 45642,
 26202,
 18549,
 18374,
 39689,
 31779,
 36272,
 16917,
 15483,
 18889,
 31657,
 49505,
 26243,
 13520,
 39514,
 36463,
 24503,
 20670,
 38475,
 20204,
 20364,
 13696,
 18758,
 28229,
 46400,
 16672,
 31857,
 10893,
 20306,
 34642,
 33583,
 27696,
 37018,
 29854,
 44687,
 40496,
 26892,
 20428,
 12396,
 26511,
 12903,
 31287,
 18903,
 17567,
 19937,
 30186,
 49655,
 13978,
 27708,
 16007,
 10612,
 16537,
 18202,
 48661,
 34326,
 18285,
 28339,
 10286,
 34234,
 17529,
 10740,
 40244,
 26222,
 27563,
 32948,
 38060,
 34682,
 10231,
 40528,
 45665,
 18489,
 37894,
 35583,
 24031,
 43417,
 40556,
 10845,
 43389,
 28518,
 41660,
 13817,
 18632,
 27552,
 29733,
 36786,
 11244,
 32196,
 14619,
 32640,
 22395,
 45074,
 19985,
 23635,
 46693,
 15071,
 11276,
 19381,
 42531,
 46571,
 43034,
 21864,
 49411,
 32857,
 42540,
 48322,
 31107,
 43315,
 22759,
 14667,
 34414,
 13317,
 39453,
 37839,
 31066,
 43895,
 27704,
 24569,
 42674,
 20503,
 18638,
 26557,
 10389,
 36273,
 29265,
 46043,
 28445,
 29732,
 15335,
 31064,
 10166,
 27250,
 41745,
 27202,
 29010,
 14843,
 28469,
 35533,
 34236,
 28132,
 20369,
 40021,
 33023,
 45397,
 17548,
 49844,
 24607,
 30547,
 25474,
 48991,
 10785,
 19383,
 45110,
 30160,
 45889,
 20673,
 32804,
 36495,
 39741,
 29370,
 25882,
 17579,
 44174,
 36252,
 24962,
 44879,
 34141,
 47656,
 10795,
 13117,
 12292,
 32593,
 15619,
 19291,
 17300,
 49987,
 18465,
 11265,
 44571,
 43612,
 34987,
 41169,
 15544,
 42374,
 25061,
 45334,
 17288,
 19495,
 40571,
 14597,
 13575,
 38307,
 13931,
 34178,
 21986,
 24637,
 44815,
 19793,
 40645,
 14200,
 26831,
 37233,
 24189,
 39912,
 25983,
 33012,
 34665,
 15958,
 17794,
 35705,
 26129,
 26342,
 47916,
 28246,
 35163,
 38033,
 31322,
 41405,
 25828,
 22685,
 42576,
 42377,
 13881,
 20554,
 27920,
 44137,
 30203,
 31457,
 31383,
 35289,
 30214,
 30068,
 13992,
 26756,
 22859,
 44549,
 22267,
 39662,
 26143,
 25755,
 36973,
 28724,
 48165,
 33838,
 16262,
 39780,
 25785,
 38010,
 17951,
 11064,
 14035,
 18851,
 47711,
 10193,
 18600,
 46542,
 39557,
 41630,
 40153,
 23069,
 13826,
 10599,
 23680,
 44134,
 10187,
 11240,
 29524,
 16290,
 38872,
 15569,
 22357,
 47294,
 41676,
 29818,
 15268,
 19225,
 33891,
 43327,
 27151,
 17157,
 10100,
 12095,
 44740,
 13971,
 25014,
 33364,
 17265,
 46881,
 15892,
 36411,
 29143,
 39343,
 48566,
 49264,
 32858,
 22698,
 39457,
 14924,
 11711,
 25916,
 30429,
 29840,
 11015,
 12553,
 22874,
 44216,
 44814,
 37367,
 12629,
 43087,
 11872,
 19674,
 32216,
 49510,
 41893,
 22374,
 43614,
 47713,
 32623,
 24628,
 24603,
 25529,
 35170,
 41976,
 20799,
 31833,
 19384,
 27636,
 17968,
 42806,
 25222,
 26804,
 34855,
 30015,
 39763,
 23375,
 39644,
 46575,
 40650,
 21255,
 45534,
 29376,
 10234,
 20519,
 21035,
 11110,
 36497,
 42521,
 15355,
 38315,
 24065,
 11849,
 29324,
 23357,
 47356,
 11707,
 17085,
 25545,
 46431,
 27716,
 31814,
 16661,
 49798,
 25609,
 47188,
 23379,
 42621,
 47778,
 14456,
 35001,
 10263,
 27463,
 21378,
 48525,
 30071,
 24830,
 27420,
 32924,
 37487,
 23795,
 34659,
 38916,
 22173,
 11712,
 35641,
 24665,
 29016,
 26137,
 19136,
 36397,
 17324,
 16938,
 19728,
 17370,
 35479,
 37995,
 31500,
 22221,
 45326,
 16723,
 37337,
 49275,
 32724,
 24167,
 45826,
 19125,
 49944,
 39823,
 22315,
 43196,
 13918,
 25495,
 24967,
 14374,
 27269,
 11446,
 14813,
 49593,
 17864,
 22828,
 33714,
 22180,
 46116,
 21668,
 36755,
 24227,
 17825,
 37293,
 46405,
 33732,
 15390,
 14566,
 34865,
 32997,
 12140,
 42047,
 19040,
 38067,
 16306,
 17557,
 34403,
 20172,
 22008,
 49495,
 15556,
 19706,
 15827,
 31246,
 47579,
 14281,
 37046,
 44948,
 13934,
 33974,
 17654,
 32620,
 30879,
 30170,
 14131,
 15477,
 15780,
 23386,
 31675,
 13011,
 27746,
 21181,
 21499,
 20057,
 18169,
 11525,
 49017,
 26875,
 21316,
 29804,
 36609,
 38421,
 47826,
 30750,
 11643,
 15787,
 26645,
 20546,
 13605,
 23223,
 29896,
 37788,
 11969,
 23769,
 35987,
 30008,
 24857,
 23996,
 37936,
 18236,
 48381,
 19610,
 41365,
 23641,
 13887,
 27826,
 15936,
 29872,
 18512,
 47889,
 16758,
 21696,
 12106,
 33924,
 28717,
 49622,
 41003,
 26247,
 22665,
 11368,
 35796,
 28367,
 15056,
 16477,
 15202,
 48694,
 41728,
 40798,
 48746,
 10425,
 34406,
 47906,
 33790,
 14799,
 11245,
 35893,
 11988,
 45102,
 26985,
 16743,
 27309,
 18906,
 24770,
 10126,
 40335,
 15728,
 45595,
 32556,
 33982,
 40111,
 37750,
 32616,
 33833,
 23915,
 11608,
 34225,
 45797,
 18194,
 13812,
 24120,
 48384,
 20859,
 25951,
 40516,
 45099,
 47399,
 48580,
 20326,
 20365,
 45777,
 25577,
 46966,
 11524,
 19143,
 25072,
 30047,
 45139,
 47742,
 45386,
 31328,
 32717,
 20504,
 47067,
 38622,
 31292,
 48475,
 15330,
 40991,
 13453,
 40392,
 28647,
 17784,
 26283,
 12610,
 10926,
 19676,
 12681,
 43102,
 41760,
 27688,
 39255,
 14393,
 35447,
 13794,
 19518,
 40180,
 44407,
 33346,
 31637,
 33041,
 27103,
 47458,
 36936,
 40381,
 16301,
 33784,
 21230,
 36311,
 32060,
 10866,
 25612,
 30914,
 20720,
 12492,
 43415,
 33387,
 47922,
 28030,
 18009,
 42893,
 12447,
 19624,
 29506,
 41231,
 14138,
 47897,
 34938,
 30799,
 12923,
 29367,
 42566,
 36071,
 25237,
 32850,
 30875,
 14734,
 34426,
 46825,
 48378,
 34463,
 48524,
 33915,
 40735,
 49409,
 41653,
 47512,
 46182,
 36741,
 32944,
 18660,
 28226,
 29454,
 25110,
 30675,
 33534,
 30714,
 28118,
 36458,
 19638,
 29927,
 49809,
 17597,
 25136,
 39864,
 39732,
 33673,
 14063,
 36551,
 23070,
 41100,
 23262,
 41649,
 27890,
 46295,
 33360,
 13432,
 46862,
 21926,
 36348,
 47848,
 32967,
 38275,
 27061,
 28082,
 19177,
 48088,
 48214,
 35802,
 27562,
 26190,
 31426,
 38292,
 44518,
 21769,
 32033,
 22360,
 42642,
 43863,
 49949,
 43988,
 31614,
 30235,
 30477,
 11808,
 14215,
 21846,
 44802,
 47891,
 42055,
 48241,
 44251,
 46515,
 11698,
 15802,
 44599,
 30789,
 43724,
 26546,
 17798,
 25424,
 44293,
 10430,
 14282,
 34114,
 30338,
 31379,
 16232,
 33616,
 28391,
 39372,
 43583,
 44036,
 48066,
 12316,
 33903,
 16412,
 35729,
 24066,
 39598,
 14204,
 30513,
 40240,
 35829,
 34219,
 48117,
 22178,
 36666,
 27476,
 28328,
 17497,
 17696,
 22232,
 34337,
 29372,
 13149,
 47222,
 26043,
 17225,
 36972,
 48840,
 31003,
 36937,
 49719,
 38250,
 45531,
 23001,
 49263,
 39578,
 20284,
 25688,
 29564,
 47752,
 20419,
 28577,
 28940,
 47244,
 12925,
 34073,
 32169,
 14607,
 28883,
 20264,
 32904,
 26830,
 22512,
 11046,
 12539,
 11652,
 14189,
 26871,
 42780,
 42723,
 29247,
 14505,
 37575,
 49711,
 16802,
 47845,
 47835,
 25873,
 23630,
 26661,
 46362,
 25694,
 23428,
 43905,
 19079,
 49385,
 38801,
 33976,
 36102,
 21687,
 24125,
 44282,
 30521,
 31425,
 20492,
 24721,
 43399,
 46312,
 34349,
 25302,
 45441,
 49383,
 24416,
 16746,
 29072,
 34897,
 14159,
 10229,
 14983,
 22200,
 23511,
 33553,
 43682,
 30575,
 38933,
 27105,
 35664,
 44360,
 35288,
 25751,
 33231,
 28385,
 28102,
 14392,
 46679,
 36970,
 29060,
 47132,
 41896,
 48003,
 13206,
 27106,
 28963,
 28397,
 22187,
 15029,
 41886,
 49093,
 40843,
 46028,
 15979,
 42730,
 32755,
 24391,
 25247,
 36569,
 31466,
 44972,
 39085,
 23803,
 35578,
 19194,
 36543,
 29096,
 12156,
 37252,
 16121,
 37597,
 21823,
 13823,
 14139,
 46199,
 12533,
 17963,
 23085,
 39243,
 29365,
 10041,
 40089,
 43804,
 16586,
 48489,
 10989,
 42276,
 18601,
 25824,
 14000,
 22653,
 27534,
 17736,
 44910,
 24850,
 27176,
 39495,
 26122,
 19669,
 10553,
 31335,
 41814,
 ...]

In [98]:
orders_df["CustomerID"] = [
    random.choice(valid_customer_ids)
    for _ in range(len(orders_df))
]

In [99]:
invalid_customer_ids = (
    set(orders_df["CustomerID"]) - set(valid_customer_ids)
)

invalid_customer_ids

set()

In [100]:
insert_dataframe2(
    orders_df,
    "Orders",
    exclude_columns=["OrderID", "CreatedAt"],
    batch_size=1000
)

Inserting into Orders: 100%|██████████| 20/20 [00:05<00:00,  3.41it/s]

In [101]:
order_items_df.columns

Index(['OrderID', 'ProductID', 'Quantity', 'UnitPrice', 'LineTotal'], dtype='object')

In [102]:
order_items_df.shape

(60075, 5)

In [103]:
orders_sql = run_query("""
SELECT OrderID
FROM Orders
""")

valid_order_ids = set(orders_sql["OrderID"])
valid_order_ids

{131072,
 131073,
 131074,
 131075,
 131076,
 131077,
 131078,
 131079,
 131080,
 131081,
 131082,
 131083,
 131084,
 131085,
 131086,
 131087,
 131088,
 131089,
 131090,
 131091,
 131092,
 131093,
 131094,
 131095,
 131096,
 131097,
 131098,
 131099,
 131100,
 131101,
 131102,
 131103,
 131104,
 131105,
 131106,
 131107,
 131108,
 131109,
 131110,
 131111,
 131112,
 131113,
 131114,
 131115,
 131116,
 131117,
 131118,
 131119,
 131120,
 131121,
 131122,
 131123,
 131124,
 131125,
 131126,
 131127,
 131128,
 131129,
 131130,
 131131,
 131132,
 131133,
 131134,
 131135,
 131136,
 131137,
 131138,
 131139,
 131140,
 131141,
 131142,
 131143,
 131144,
 131145,
 131146,
 131147,
 131148,
 131149,
 131150,
 131151,
 131152,
 131153,
 131154,
 131155,
 131156,
 131157,
 131158,
 131159,
 131160,
 131161,
 131162,
 131163,
 131164,
 131165,
 131166,
 131167,
 131168,
 131169,
 131170,
 131171,
 131172,
 131173,
 131174,
 131175,
 131176,
 131177,
 131178,
 131179,
 131180,
 131181,
 131182,
 131183,
 131184,
 131185,
 131186,
 131187,
 131188,
 131189,
 131190,
 131191,
 131192,
 131193,
 131194,
 131195,
 131196,
 131197,
 131198,
 131199,
 131200,
 131201,
 131202,
 131203,
 131204,
 131205,
 131206,
 131207,
 131208,
 131209,
 131210,
 131211,
 131212,
 131213,
 131214,
 131215,
 131216,
 131217,
 131218,
 131219,
 131220,
 131221,
 131222,
 131223,
 131224,
 131225,
 131226,
 131227,
 131228,
 131229,
 131230,
 131231,
 131232,
 131233,
 131234,
 131235,
 131236,
 131237,
 131238,
 131239,
 131240,
 131241,
 131242,
 131243,
 131244,
 131245,
 131246,
 131247,
 131248,
 131249,
 131250,
 131251,
 131252,
 131253,
 131254,
 131255,
 131256,
 131257,
 131258,
 131259,
 131260,
 131261,
 131262,
 131263,
 131264,
 131265,
 131266,
 131267,
 131268,
 131269,
 131270,
 131271,
 131272,
 131273,
 131274,
 131275,
 131276,
 131277,
 131278,
 131279,
 131280,
 131281,
 131282,
 131283,
 131284,
 131285,
 131286,
 131287,
 131288,
 131289,
 131290,
 131291,
 131292,
 131293,
 131294,
 131295,
 131296,
 131297,
 131298,
 131299,
 131300,
 131301,
 131302,
 131303,
 131304,
 131305,
 131306,
 131307,
 131308,
 131309,
 131310,
 131311,
 131312,
 131313,
 131314,
 131315,
 131316,
 131317,
 131318,
 131319,
 131320,
 131321,
 131322,
 131323,
 131324,
 131325,
 131326,
 131327,
 131328,
 131329,
 131330,
 131331,
 131332,
 131333,
 131334,
 131335,
 131336,
 131337,
 131338,
 131339,
 131340,
 131341,
 131342,
 131343,
 131344,
 131345,
 131346,
 131347,
 131348,
 131349,
 131350,
 131351,
 131352,
 131353,
 131354,
 131355,
 131356,
 131357,
 131358,
 131359,
 131360,
 131361,
 131362,
 131363,
 131364,
 131365,
 131366,
 131367,
 131368,
 131369,
 131370,
 131371,
 131372,
 131373,
 131374,
 131375,
 131376,
 131377,
 131378,
 131379,
 131380,
 131381,
 131382,
 131383,
 131384,
 131385,
 131386,
 131387,
 131388,
 131389,
 131390,
 131391,
 131392,
 131393,
 131394,
 131395,
 131396,
 131397,
 131398,
 131399,
 131400,
 131401,
 131402,
 131403,
 131404,
 131405,
 131406,
 131407,
 131408,
 131409,
 131410,
 131411,
 131412,
 131413,
 131414,
 131415,
 131416,
 131417,
 131418,
 131419,
 131420,
 131421,
 131422,
 131423,
 131424,
 131425,
 131426,
 131427,
 131428,
 131429,
 131430,
 131431,
 131432,
 131433,
 131434,
 131435,
 131436,
 131437,
 131438,
 131439,
 131440,
 131441,
 131442,
 131443,
 131444,
 131445,
 131446,
 131447,
 131448,
 131449,
 131450,
 131451,
 131452,
 131453,
 131454,
 131455,
 131456,
 131457,
 131458,
 131459,
 131460,
 131461,
 131462,
 131463,
 131464,
 131465,
 131466,
 131467,
 131468,
 131469,
 131470,
 131471,
 131472,
 131473,
 131474,
 131475,
 131476,
 131477,
 131478,
 131479,
 131480,
 131481,
 131482,
 131483,
 131484,
 131485,
 131486,
 131487,
 131488,
 131489,
 131490,
 131491,
 131492,
 131493,
 131494,
 131495,
 131496,
 131497,
 131498,
 131499,
 131500,
 131501,
 131502,
 131503,
 131504,
 131505,
 131506,
 131507,
 131508,
 131509,
 131510,
 131511,
 131512,
 131513,
 131514,
 131515,
 131516,
 131517,
 131518,
 131519,
 131520,
 131521,
 131522,
 131523,
 131524,
 131525,
 131526,
 131527,
 131528,
 131529,
 131530,
 131531,
 131532,
 131533,
 131534,
 131535,
 131536,
 131537,
 131538,
 131539,
 131540,
 131541,
 131542,
 131543,
 131544,
 131545,
 131546,
 131547,
 131548,
 131549,
 131550,
 131551,
 131552,
 131553,
 131554,
 131555,
 131556,
 131557,
 131558,
 131559,
 131560,
 131561,
 131562,
 131563,
 131564,
 131565,
 131566,
 131567,
 131568,
 131569,
 131570,
 131571,
 131572,
 131573,
 131574,
 131575,
 131576,
 131577,
 131578,
 131579,
 131580,
 131581,
 131582,
 131583,
 131584,
 131585,
 131586,
 131587,
 131588,
 131589,
 131590,
 131591,
 131592,
 131593,
 131594,
 131595,
 131596,
 131597,
 131598,
 131599,
 131600,
 131601,
 131602,
 131603,
 131604,
 131605,
 131606,
 131607,
 131608,
 131609,
 131610,
 131611,
 131612,
 131613,
 131614,
 131615,
 131616,
 131617,
 131618,
 131619,
 131620,
 131621,
 131622,
 131623,
 131624,
 131625,
 131626,
 131627,
 131628,
 131629,
 131630,
 131631,
 131632,
 131633,
 131634,
 131635,
 131636,
 131637,
 131638,
 131639,
 131640,
 131641,
 131642,
 131643,
 131644,
 131645,
 131646,
 131647,
 131648,
 131649,
 131650,
 131651,
 131652,
 131653,
 131654,
 131655,
 131656,
 131657,
 131658,
 131659,
 131660,
 131661,
 131662,
 131663,
 131664,
 131665,
 131666,
 131667,
 131668,
 131669,
 131670,
 131671,
 131672,
 131673,
 131674,
 131675,
 131676,
 131677,
 131678,
 131679,
 131680,
 131681,
 131682,
 131683,
 131684,
 131685,
 131686,
 131687,
 131688,
 131689,
 131690,
 131691,
 131692,
 131693,
 131694,
 131695,
 131696,
 131697,
 131698,
 131699,
 131700,
 131701,
 131702,
 131703,
 131704,
 131705,
 131706,
 131707,
 131708,
 131709,
 131710,
 131711,
 131712,
 131713,
 131714,
 131715,
 131716,
 131717,
 131718,
 131719,
 131720,
 131721,
 131722,
 131723,
 131724,
 131725,
 131726,
 131727,
 131728,
 131729,
 131730,
 131731,
 131732,
 131733,
 131734,
 131735,
 131736,
 131737,
 131738,
 131739,
 131740,
 131741,
 131742,
 131743,
 131744,
 131745,
 131746,
 131747,
 131748,
 131749,
 131750,
 131751,
 131752,
 131753,
 131754,
 131755,
 131756,
 131757,
 131758,
 131759,
 131760,
 131761,
 131762,
 131763,
 131764,
 131765,
 131766,
 131767,
 131768,
 131769,
 131770,
 131771,
 131772,
 131773,
 131774,
 131775,
 131776,
 131777,
 131778,
 131779,
 131780,
 131781,
 131782,
 131783,
 131784,
 131785,
 131786,
 131787,
 131788,
 131789,
 131790,
 131791,
 131792,
 131793,
 131794,
 131795,
 131796,
 131797,
 131798,
 131799,
 131800,
 131801,
 131802,
 131803,
 131804,
 131805,
 131806,
 131807,
 131808,
 131809,
 131810,
 131811,
 131812,
 131813,
 131814,
 131815,
 131816,
 131817,
 131818,
 131819,
 131820,
 131821,
 131822,
 131823,
 131824,
 131825,
 131826,
 131827,
 131828,
 131829,
 131830,
 131831,
 131832,
 131833,
 131834,
 131835,
 131836,
 131837,
 131838,
 131839,
 131840,
 131841,
 131842,
 131843,
 131844,
 131845,
 131846,
 131847,
 131848,
 131849,
 131850,
 131851,
 131852,
 131853,
 131854,
 131855,
 131856,
 131857,
 131858,
 131859,
 131860,
 131861,
 131862,
 131863,
 131864,
 131865,
 131866,
 131867,
 131868,
 131869,
 131870,
 131871,
 131872,
 131873,
 131874,
 131875,
 131876,
 131877,
 131878,
 131879,
 131880,
 131881,
 131882,
 131883,
 131884,
 131885,
 131886,
 131887,
 131888,
 131889,
 131890,
 131891,
 131892,
 131893,
 131894,
 131895,
 131896,
 131897,
 131898,
 131899,
 131900,
 131901,
 131902,
 131903,
 131904,
 131905,
 131906,
 131907,
 131908,
 131909,
 131910,
 131911,
 131912,
 131913,
 131914,
 131915,
 131916,
 131917,
 131918,
 131919,
 131920,
 131921,
 131922,
 131923,
 131924,
 131925,
 131926,
 131927,
 131928,
 131929,
 131930,
 131931,
 131932,
 131933,
 131934,
 131935,
 131936,
 131937,
 131938,
 131939,
 131940,
 131941,
 131942,
 131943,
 131944,
 131945,
 131946,
 131947,
 131948,
 131949,
 131950,
 131951,
 131952,
 131953,
 131954,
 131955,
 131956,
 131957,
 131958,
 131959,
 131960,
 131961,
 131962,
 131963,
 131964,
 131965,
 131966,
 131967,
 131968,
 131969,
 131970,
 131971,
 131972,
 131973,
 131974,
 131975,
 131976,
 131977,
 131978,
 131979,
 131980,
 131981,
 131982,
 131983,
 131984,
 131985,
 131986,
 131987,
 131988,
 131989,
 131990,
 131991,
 131992,
 131993,
 131994,
 131995,
 131996,
 131997,
 131998,
 131999,
 132000,
 132001,
 132002,
 132003,
 132004,
 132005,
 132006,
 132007,
 132008,
 132009,
 132010,
 132011,
 132012,
 132013,
 132014,
 132015,
 132016,
 132017,
 132018,
 132019,
 132020,
 132021,
 132022,
 132023,
 132024,
 132025,
 132026,
 132027,
 132028,
 132029,
 132030,
 132031,
 132032,
 132033,
 132034,
 132035,
 132036,
 132037,
 132038,
 132039,
 132040,
 132041,
 132042,
 132043,
 132044,
 132045,
 132046,
 132047,
 132048,
 132049,
 132050,
 132051,
 132052,
 132053,
 132054,
 132055,
 132056,
 132057,
 132058,
 132059,
 132060,
 132061,
 132062,
 132063,
 132064,
 132065,
 132066,
 132067,
 132068,
 132069,
 132070,
 132071,
 ...}

In [104]:
products_sql = run_query("""
SELECT ProductID
FROM Products
""")

valid_product_ids = set(products_sql["ProductID"])
valid_product_ids

{2,
 3,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 533,
 535,
 536,
 537,
 540,
 541,
 542,
 545,
 546,
 547,
 550,
 551,
 552,
 553,
 555,
 556,
 557,
 558,
 560,
 561,
 562,
 564,
 565,
 566,
 567,
 569,
 570,
 571,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 583,
 584,
 585,
 586,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 598,
 599,
 601,
 602,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 641,
 642,
 643,
 644,
 645,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 658,
 659,
 660,
 661,
 663,
 664,
 665,
 666,
 668,
 669,
 671,
 672,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 683,
 684,
 685,
 686,
 687,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 700,
 701,
 702,
 705,
 706,
 708,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 720,
 721,
 722,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 735,
 736,
 738,
 739,
 740,
 741,
 742,
 744,
 746,
 748,
 749,
 750,
 751,
 752,
 754,
 756,
 757,
 759,
 760,
 762,
 763,
 764,
 765,
 766,
 768,
 769,
 770,
 771,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 788,
 789,
 790,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 808,
 809,
 810,
 811,
 812,
 813,
 816,
 817,
 818,
 819,
 821,
 822,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 832,
 833,
 835,
 836,
 837,
 838,
 839,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 862,
 864,
 865,
 866,
 867,
 868,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 892,
 893,
 894,
 895,
 896,
 898,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 910,
 911,
 912,
 913,
 915,
 916,
 917,
 918,
 919,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 964,
 965,
 966,
 967,
 968,
 970,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1033,
 1035,
 1036,
 1037,
 1040,
 1041,
 1042,
 1045,
 1046,
 1047,
 1050,
 1051,
 1052,
 1053,
 1055,
 1056,
 1057,
 1058,
 1060,
 1061,
 1062,
 1064,
 1065,
 1066,
 1067,
 1069,
 1070,
 1071,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1083,
 1084,
 1085,
 1086,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1098,
 1099,
 1101,
 1102,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1141,
 1142,
 1143,
 1144,
 1145,
 1148,
 1149,
 1150,
 1151,
 1152,
 1153,
 1154,
 1155,
 1156,
 1158,
 1159,
 1160,
 1161,
 1163,
 1164,
 1165,
 1166,
 1168,
 1169,
 1171,
 1172,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1183,
 1184,
 1185,
 1186,
 1187,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1200,
 1201,
 1202,
 1205,
 1206,
 1208,
 1210,
 1211,
 1212,
 1213,
 1214,
 1215,
 1216,
 1217,
 1218,
 1220,
 1221,
 1222,
 1224,
 1225,
 1226,
 1227,
 1228,
 1229,
 1230,
 1231,
 1232,
 1235,
 1236,
 1238,
 1239,
 1240,
 1241,
 1242,
 1244,
 1246,
 1248,
 1249,
 1250,
 1251,
 1252,
 1254,
 1256,
 1257,
 1259,
 1260,
 1262,
 1263,
 1264,
 1265,
 1266,
 1268,
 1269,
 1270,
 1271,
 1273,
 1274,
 1275,
 1276,
 1277,
 1278,
 1279,
 1280,
 1281,
 1282,
 1283,
 1284,
 1285,
 1286,
 1288,
 1289,
 1290,
 1294,
 1295,
 1296,
 1297,
 1298,
 1299,
 1300,
 1301,
 1302,
 1303,
 1304,
 1305,
 1306,
 1308,
 1309,
 1310,
 1311,
 1312,
 1313,
 1316,
 1317,
 1318,
 1319,
 1321,
 1322,
 1324,
 1325,
 1326,
 1327,
 1328,
 1329,
 1330,
 1332,
 1333,
 1335,
 1336,
 1337,
 1338,
 1339,
 1341,
 1342,
 1343,
 1344,
 1345,
 1346,
 1347,
 1348,
 1349,
 1351,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1358,
 1359,
 1360,
 1362,
 1364,
 1365,
 1366,
 1367,
 1368,
 1371,
 1372,
 1373,
 1374,
 1375,
 1376,
 1377,
 1378,
 1379,
 1380,
 1382,
 1383,
 1384,
 1385,
 1386,
 1387,
 1388,
 1389,
 1392,
 1393,
 1394,
 1395,
 1396,
 1398,
 1400,
 1401,
 1402,
 1403,
 1404,
 1405,
 1406,
 1407,
 1408,
 1410,
 1411,
 1412,
 1413,
 1415,
 1416,
 1417,
 1418,
 1419,
 1421,
 1422,
 1423,
 1424,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1431,
 1432,
 1433,
 1434,
 1435,
 1436,
 1437,
 1438,
 1439,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1446,
 1447,
 1448,
 1451,
 1452,
 1453,
 1454,
 1455,
 1456,
 1457,
 1458,
 1459,
 1460,
 1461,
 1462,
 1464,
 1465,
 1466,
 1467,
 1468,
 1470,
 1472,
 1473,
 1474,
 1475,
 1476,
 1477,
 1478,
 1479,
 1480,
 1481,
 1482,
 1483,
 1484,
 1485,
 1486,
 1487,
 1488,
 1489,
 1490,
 1491,
 1493,
 1494,
 1495,
 1496,
 1497,
 1498,
 1499,
 1500,
 1501,
 1502,
 1503,
 1504,
 1505,
 1506,
 1507,
 1508,
 1509,
 1510,
 1511,
 1512,
 1513,
 1514,
 1515,
 1516,
 1517,
 1518,
 1519,
 1520,
 1521,
 1522,
 1523,
 1524,
 1525,
 1526,
 1527,
 1528,
 1529,
 1530,
 1531,
 1532,
 1533,
 1534,
 1535,
 1536,
 1537,
 1538,
 1539,
 1540,
 1541,
 1542,
 1543,
 1544,
 1545,
 1546,
 1547,
 1548,
 1549,
 1550,
 1551,
 1552,
 1553,
 1554,
 1555,
 1556,
 1557,
 1558,
 1559,
 1560,
 1561,
 1562,
 1563,
 1564,
 1565,
 1566,
 1567,
 1568,
 1569,
 1570,
 1571,
 1572,
 1573,
 1574,
 1575,
 1576,
 1577,
 1578,
 1579,
 1580,
 1581,
 1582,
 1583,
 1584,
 1585,
 1586,
 1587,
 1588,
 1589,
 1590,
 1591,
 1592,
 1593,
 1594,
 1595,
 1596,
 1597,
 1598,
 1599,
 1600,
 1601,
 1602,
 1603,
 1604,
 1605,
 1606,
 1607,
 1608,
 1609,
 1610,
 1611,
 1612,
 1613,
 1614,
 1615,
 1616,
 1617,
 1618,
 1619,
 1620,
 1621,
 1622,
 1623,
 1624,
 1625,
 1626,
 1627,
 1628,
 1629,
 1630,
 1631,
 1632,
 1633,
 1634,
 1635,
 1636,
 1637,
 1638,
 1639,
 1640,
 1641,
 1642,
 1643,
 1644,
 1645,
 1646,
 1647,
 1648,
 1649,
 1650,
 1651,
 1652,
 1653,
 1654,
 1655,
 1656,
 1657,
 1658,
 1659,
 1660,
 1661,
 1662,
 1663,
 1664,
 1665,
 1666,
 1667,
 1668,
 1669,
 ...}

In [105]:
invalid_order_ids = (
    set(order_items_df["OrderID"]) - valid_order_ids
)

invalid_product_ids = (
    set(order_items_df["ProductID"]) - valid_product_ids
)

In [106]:

invalid_order_ids

{1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 ...}

In [107]:
valid_order_ids = orders_sql["OrderID"].tolist()
order_items_df["OrderID"] = [
    random.choice(valid_order_ids)
    for _ in range(len(order_items_df))
]

In [108]:
valid_product_ids = products_sql["ProductID"].tolist()
order_items_df["ProductID"] = [
    random.choice(valid_product_ids)
    for _ in range(len(order_items_df))
]

In [109]:
invalid_order_ids = (
    set(order_items_df["OrderID"]) - set(valid_order_ids)
)

invalid_product_ids = (
    set(order_items_df["ProductID"]) - set(valid_product_ids)
)

print(invalid_order_ids)
print(invalid_product_ids)

set()
set()

In [110]:
order_items_df["Discount"] = [
    round(random.uniform(0, row["LineTotal"] * 0.2), 2)
    for _, row in order_items_df.iterrows()
]

In [111]:
insert_dataframe2(
    order_items_df,
    "OrderItems",
    exclude_columns=["LineTotal", "OrderItemID", "CreatedAt"],
    batch_size=1000
)

Inserting into OrderItems: 100%|██████████| 61/61 [00:10<00:00,  5.91it/s]

In [112]:
run_query("""
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'OrderItems'
ORDER BY ORDINAL_POSITION
""")

,COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE
0,OrderItemID,int,None,10.0,0.0
1,OrderID,int,None,10.0,0.0
2,ProductID,int,None,10.0,0.0
3,Quantity,int,None,10.0,0.0
4,UnitPrice,decimal,None,10.0,2.0
5,Discount,decimal,None,10.0,2.0
6,CreatedAt,datetime2,None,NaN,NaN

In [113]:
len(order_items_df)

60075